spring:
  application:
    name: gateway

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Logging
logging:
  level:
    com.hsurveys.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG 