spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # User Service Routes
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**,/api/auth/**,/api/roles/**,/api/permissions/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@redisRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
            - name: JwtAuthentication
            # Add DedupeResponseHeader to remove duplicate CORS headers
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
                strategy: RETAIN_FIRST

        # Organization Service Routes
        - id: organization-service
          uri: http://organization-service:8080
          predicates:
            - Path=/api/organizations/**,/api/departments/**,/api/teams/**
          filters:
            - name: CircuitBreaker
              args:
                name: organization-service
                fallbackUri: forward:/fallback/organization-service
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@redisRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
            - name: JwtAuthentication
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
                strategy: RETAIN_FIRST

        # Survey Service Routes
        - id: survey-service
          uri: http://survey-service:8080
          predicates:
            - Path=/api/surveys/**,/api/questions/**,/api/options/**
          filters:
            - name: CircuitBreaker
              args:
                name: survey-service
                fallbackUri: forward:/fallback/survey-service
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@redisRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
            - name: JwtAuthentication
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
                strategy: RETAIN_FIRST

      # Alternative: Use global default filters for all routes
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin Access-Control-Allow-Credentials Vary
            strategy: RETAIN_FIRST

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:900000}

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      organization-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      survey-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

  timelimiter:
    instances:
      user-service:
        timeoutDuration: 4s
      organization-service:
        timeoutDuration: 4s
      survey-service:
        timeoutDuration: 4s

# Redis Configuration (for rate limiting)
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}

# Rate Limiting Configuration
rate-limit:
  replenish-rate: 10
  burst-capacity: 20
  requested-tokens: 1

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,circuitbreakers,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Logging Configuration
logging:
  level:
    # Keep your application logs at DEBUG for useful debugging
    com.hsurveys.gateway: DEBUG

    # Reduce Spring Cloud Gateway noise to WARN (only show problems)
    org.springframework.cloud.gateway: WARN

    # Silence the noisy Netty connection logs completely
    reactor.netty: WARN
    reactor.netty.resources: WARN
    reactor.netty.http.client: WARN
    reactor.netty.http.server: WARN

    # Silence connection pool logs specifically
    reactor.netty.resources.DefaultPooledConnectionProvider: WARN

    # Keep circuit breaker logs useful
    io.github.resilience4j: INFO

    # Keep Spring Boot essentials
    org.springframework.boot: INFO
    org.springframework.web: INFO

    # Root logger - catch anything else
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"