spring:
  application:
    name: gateway

server:
  port: 8080

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:900000}

# Logging
logging:
  level:
    com.hsurveys.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG 